   # docker-compose.yml - Rand-A-Pizza
version: "3.8"

services:
  backend:
    build:
      context: ./../
      dockerfile: Dockerfile_backend
    container_name: backend
    ports:
      - "8000:8000"
    #env_file:          # Local .env uncomment if you're working locally
     # - .env
    volumes:
      - ./backend:/backend
    environment:  # GitHub Secrets (Render)
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  frontend:
     build:
       context: ./../  # Build from the frontend folder in the root directory
       dockerfile: Dockerfile_frontend  # Ensure the correct Dockerfile is used
     container_name: frontend
     ports:
       - "3001:3000"
     volumes:
       - ./frontend:/frontend # Mount the frontend folder into the container
     command: npm run dev -- --host 0.0.0.0
     depends_on:
       - backend
#     # stdin_open: true
#     # tty: true
#    # command: sleep infinity  # Keep the container running
