   # docker-compose.yml - Rand-A-Pizza
version: "3.8"

services:
  backend:
    build:
      context: ./../
      dockerfile: Dockerfile_backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:          # Local .env (ignored by Git)
      - .env
    volumes:
      - ./backend:/app  # Hot reload
    environment:       # GitHub Secrets override (production)
      - SUPABASE_URL
      - SUPABASE_KEY
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  frontend:
    build:
      context: ./../  # Build from the frontend folder in the root directory
      dockerfile: Dockerfile_frontend  # Ensure the correct Dockerfile is used
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend  # Mount the frontend folder into the container
    # stdin_open: true
    # tty: true
   # command: sleep infinity  # Keep the container running