# docker-compose.yml - Rand-A-Pizza
version: "3.8"

services:
  backend:
    build:
      context: ./../
      dockerfile: Dockerfile_backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    # restart: unless-stopped
    # env_file: .env  # Local .env (ignored by Git)

  frontend:
    build:
      context: ./../  # Build from the frontend folder in the root directory
      dockerfile: Dockerfile_frontend  # Ensure the correct Dockerfile is used
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend  # Mount the frontend folder into the container
    # stdin_open: true
    # tty: true
    # command: sleep infinity  # Keep the container running
