services:
  backend:
    build:
      context: ./../
      dockerfile: Dockerfile_backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./backend:/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    # command: sleep infinity  # Keep the container running

  frontend:
    build:
      context: ./../  # Build from the frontend folder in the root directory
      dockerfile: Dockerfile_frontend  # Ensure the correct Dockerfile is used
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend  # Mount the frontend folder into the container
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      


